# Generated by Django 4.1.7 on 2023-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tagsnews_alter_article_options_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsnews',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='articles.article'),
        ),
    ]
