# Generated by Django 4.1.7 on 2023-03-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tagsnews_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsnews',
            name='name',
        ),
    ]
