# Generated by Django 4.1.7 on 2023-03-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_tagsnews_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsnews',
            name='article',
            field=models.ManyToManyField(related_name='Раздел', to='articles.article'),
        ),
    ]
