# Generated by Django 4.1.7 on 2023-03-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_tagsnews_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'default_related_name': 'scopes', 'verbose_name': 'Раздел', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tagsnews', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='tagsnews',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='articles.article'),
        ),
    ]
