# Generated by Django 4.1.7 on 2023-03-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_options_alter_scope_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Тег'),
        ),
    ]
