# Generated by Django 4.1.7 on 2023-03-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_scope_name'),
    ]

    operations = [
    ]
