# Generated by Django 4.1.7 on 2023-03-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20230309_1451'),
    ]

    operations = [
    ]
