# Generated by Django 4.1.7 on 2023-03-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_teacher_teacherstudent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherstudent',
            options={'default_related_name': 'teacher_student', 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя учеников'},
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherstudent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='school.student', verbose_name='Учитель'),
        ),
    ]
